security:
    providers:
        in_memory:
            memory:
                users:
                    admin: { password: admin }

    firewalls:
        secured_area:
            pattern: ^
            anonymous: ~
